
import type {
  Team,
  StrategyState,
  RadarItemType,
  RadarCategory,
  RadarDistance,
  RadarImpact,
  RadarTolerance,
  Initiative,
  InitiativeStep,
} from './types';

const newInitiativeTemplate = (id: string, name: string): Initiative => ({
  id,
  name,
  progression: 0,
  steps: initiativeStepsTemplate.map((step) => ({
    key: step.key,
    title: step.title,
    iconName: step.iconName,
    items: [],
  })),
  linkedRadarItemIds: [],
});

const initiativeStepsTemplate: {
  key: 'diagnostic' | 'overallApproach' | 'actions' | 'proximateObjectives';
  title: string;
  iconName: string;
}[] = [
  { key: 'diagnostic', title: 'Diagnostic', iconName: 'Search' },
  { key: 'overallApproach', title: 'Overall Approach', iconName: 'Milestone' },
  { key: 'actions', title: 'Actions', iconName: 'ListChecks' },
  { key: 'proximateObjectives', title: 'Proximate Objectives', iconName: 'Target' },
];

export const initialTeams: Omit<Team, 'companyId'>[] = [
  {
    id: 'team-bod',
    name: 'Board of Directors',
    purpose: 'Oversees the company\'s direction.',
    context: 'Highest governing body.',
    level: 0,
    dashboard: {
      id: 'dashboard-bod',
      name: 'Board-Level Strategic Goals',
      strategies: [
        {
          id: 'bod-strat-1',
          description: 'Grow market share by 5% YoY',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            {
              id: 'init-bod-1',
              name: 'Board Priority: Market Expansion',
              progression: 15,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-bod-2',
              name: 'Board Priority: ESG Disclosure',
              progression: 10,
              steps: [],
              linkedRadarItemIds: [],
            },
          ],
        },
      ],
    },
    radar: [
  {
    id: 'radar-bod-ai-governance',
    radarId: 'team-bod',
    name: 'AI Governance & Ethics',
    detect: 'Regulators are tightening AI oversight and ethical standards.',
    assess: 'High risk if company lacks AI transparency and accountability frameworks.',
    respond: 'Mandate AI governance board and require annual AI audit.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-esg',
    radarId: 'team-bod',
    name: 'ESG & Sustainability Mandates',
    detect: 'Investors and governments increasing ESG reporting pressure.',
    assess: 'Essential for investor confidence and license to operate.',
    respond: 'Integrate ESG metrics into strategic KPIs and executive comp.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-geopolitical-risk',
    radarId: 'team-bod',
    name: 'Geopolitical & Supply Chain Risk',
    detect: 'Global tensions disrupting supply chains and talent flow.',
    assess: 'Exposure to geopolitical shocks increasing operational risk.',
    respond: 'Diversify suppliers and assess nearshoring opportunities.',
    type: 'Threat',
    category: 'Operating Model',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-capital-markets',
    radarId: 'team-bod',
    name: 'Capital Market Volatility',
    detect: 'Interest rate uncertainty affecting valuations and M&A.',
    assess: 'Reduced investor appetite for high-risk growth strategies.',
    respond: 'Review capital allocation and strengthen balance sheet resilience.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-board-composition',
    radarId: 'team-bod',
    name: 'Board Composition & Digital Literacy',
    detect: 'Boards increasingly expected to understand AI and cybersecurity.',
    assess: 'Current board skills gap could slow oversight of digital strategy.',
    respond: 'Recruit directors with data and technology expertise.',
    type: 'Opportunity',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-transparency',
    radarId: 'team-bod',
    name: 'Transparency & Stakeholder Trust',
    detect: 'Public trust in corporations under pressure; rising activism.',
    assess: 'Reputation risk can impact valuation and talent attraction.',
    respond: 'Enhance disclosure practices and stakeholder communication.',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Detected',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-succession',
    radarId: 'team-bod',
    name: 'Leadership Succession Planning',
    detect: 'CEO transitions are increasingly high-risk events.',
    assess: 'Lack of robust succession plan creates strategic vulnerability.',
    respond: 'Establish formal succession and emergency transition plan.',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
],
  },
  {
    id: 'team-ceo',
    name: 'CEO',
    purpose: 'Leads the company and executes the board\'s vision.',
    context: 'Chief Executive Officer.',
    level: 1,
    dashboard: {
      id: 'dashboard-ceo',
      name: 'CEO Directives',
      strategies: [
        {
          id: 'ceo-strat-1',
          description: 'Execute on Q4 2024 Product Launch',
          timeframe: 'Q4 2024',
          state: 'Active',
          initiatives: [
            {
              id: 'init-ceo-1-1',
              name: 'Define launch narrative',
              progression: 20,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-ceo-1-2',
              name: 'Align leadership OKRs',
              progression: 10,
              steps: [],
              linkedRadarItemIds: [],
            },
          ],
        },
        {
          id: 'ceo-strat-2',
          description: 'Improve operational efficiency',
          timeframe: '2025',
          state: 'Draft',
          initiatives: [],
        },
      ],
    },
    radar: [
  {
    id: 'radar-ceo-ai-productivity',
    radarId: 'team-ceo',
    name: 'AI-Driven Productivity',
    detect: 'Competitors achieving efficiency gains through generative AI.',
    assess: 'Significant opportunity to enhance output per employee.',
    respond: 'Deploy AI copilots across key business functions by Q2 2025.',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-talent-retention',
    radarId: 'team-ceo',
    name: 'Talent Retention & Hybrid Work',
    detect: 'Employee engagement declining post-pandemic.',
    assess: 'Attrition risk in high-skill roles; hybrid model inconsistencies.',
    respond: 'Redefine EVP around flexibility, purpose, and growth.',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-innovation-pipeline',
    radarId: 'team-ceo',
    name: 'Innovation Pipeline',
    detect: 'Slow time-to-market for new initiatives.',
    assess: 'Innovation velocity lags competitors.',
    respond: 'Create cross-functional innovation squads with funding autonomy.',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-customer-trust',
    radarId: 'team-ceo',
    name: 'Customer Trust & Data Privacy',
    detect: 'Increasing public concern about data use and AI bias.',
    assess: 'Potential reputational and legal impact.',
    respond: 'Implement privacy-by-design policy and transparency dashboards.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-operational-efficiency',
    radarId: 'team-ceo',
    name: 'Operational Efficiency',
    detect: 'Duplication and misalignment across divisions.',
    assess: 'Structural inefficiencies reducing agility and profit margins.',
    respond: 'Introduce zero-based design and OKR-driven governance.',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-digital-transformation',
    radarId: 'team-ceo',
    name: 'Digital Transformation Fatigue',
    detect: 'Multiple digital programs without unified vision.',
    assess: 'Risk of initiative overload and cultural resistance.',
    respond: 'Streamline digital portfolio and align with customer value streams.',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-mna-opportunity',
    radarId: 'team-ceo',
    name: 'Strategic M&A Opportunities',
    detect: 'Valuations in target markets have declined.',
    assess: 'Potential for inorganic growth in adjacent technologies.',
    respond: 'Evaluate 2–3 acquisition candidates by Q1 2025.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-brand-differentiation',
    radarId: 'team-ceo',
    name: 'Brand Differentiation',
    detect: 'Commoditization in our core market.',
    assess: 'Weak differentiation undermines pricing power.',
    respond: 'Pivot brand narrative to innovation, trust, and sustainability.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
],
  },
  {
    id: 'team-cfo',
    name: 'CFO',
    purpose: 'Manages the company\'s finances.',
    context: 'Chief Financial Officer',
    level: 2,
    dashboard: { id: 'dashboard-cfo', name: 'Financial Strategy', strategies: [] },
    radar: [],
  },
  {
    id: 'team-cto',
    name: 'CTO',
    purpose: 'Leads technology and engineering.',
    context: 'Chief Technology Officer',
    level: 2,
    dashboard: {
      id: 'dashboard-cto-1',
      name: 'Technology Roadmap',
      strategies: [
        {
          id: 'strat-1',
          description: 'Develop and launch the new \'Innovate\' feature set.',
          timeframe: 'Q4 2024',
          state: 'Active',
          initiatives: [
            {
              id: 'init-1-1',
              name: 'Market Research & Analysis',
              progression: 80,
              steps: [
                {
                  key: 'diagnostic',
                  title: 'Diagnostic',
                  iconName: 'Search',
                  items: [
                    { id: 'item-1', text: 'Analyze competitor pricing' },
                    { id: 'item-2', text: 'Survey target user base' },
                  ],
                },
                {
                  key: 'overallApproach',
                  title: 'Overall Approach',
                  iconName: 'Milestone',
                  items: [{ id: 'item-3', text: 'Define phased rollout plan' }],
                },
                { key: 'actions', title: 'Actions', iconName: 'ListChecks', items: [] },
                {
                  key: 'proximateObjectives',
                  title: 'Proximate Objectives',
                  iconName: 'Target',
                  items: [{ id: 'item-4', text: 'Achieve 500 survey responses' }],
                },
              ],
              linkedRadarItemIds: ['radar-item-1'],
            },
            {
              id: 'init-1-2',
              name: 'MVP Scope & Architecture',
              progression: 40,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-1-3',
              name: 'Pilot Rollout',
              progression: 5,
              steps: [],
              linkedRadarItemIds: [],
            },
          ],
        },
        {
          id: 'strat-2',
          description: 'Marketing and go-to-market strategy.',
          timeframe: 'Q4 2024',
          state: 'Draft',
          initiatives: [],
        },
      ],
    },
    radar: [
      {
        id: 'radar-item-1',
        radarId: 'team-cto',
        name: 'AI-driven Automation',
        detect: 'Competitors are leveraging AI to automate customer support.',
        assess: 'This poses a medium-term threat to our market position if we don\'t adapt. It could reduce our operational costs significantly.',
        respond: 'Initiate a pilot project to explore AI chatbot solutions for customer service.',
        type: 'Opportunity',
        category: 'Operating Model',
        distance: 'Detected',
        impact: 'Medium',
        tolerance: 'Medium',
        zoom_in: null,
        created_at: new Date().toISOString(),
        updated_at: null,
      },
      {
    id: 'radar-item-roles-of-sm-ba-pm',
    radarId: 'team-cto',
    name: 'Roles of SM, BA, PM',
    detect: 'What is their role with AI?',
    assess: 'Adaptation required towards facilitators',
    respond: 'trainings',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-cultural-inertia',
    radarId: 'team-cto',
    name: 'Cultural Inertia',
    detect: 'Cultural Inertia: This form refers to deep-rooted norms and mindsets within an organization that resist change. An example is AT&T’s struggle in the mid-1980s to transition from a monopolistic structure to an innovative tech company, hindered by its culture which was focused more on research than on product development.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Detected',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-flow-engineering',
    radarId: 'team-cto',
    name: 'Flow Engineering',
    detect: 'We need to kill silos',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-unit-slices',
    radarId: 'team-cto',
    name: 'Unit / Slices',
    detect: 'Slices (of capabilities) should be our new unit of work/effort',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-driven-spec',
    radarId: 'team-cto',
    name: 'driven spec',
    detect: 'to find ou more',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-ai',
    radarId: 'team-cto',
    name: 'AI',
    detect: 'tactically vs. strategically vs. Hype',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-slice-architecture',
    radarId: 'team-cto',
    name: 'Slice Architecture',
    detect: 'Lack of consistency in the way we design/implement our software solutions. VSA (Vertical Slice Architecture) should give us clear directions',
    assess: 'Easy to understand, works well with Event Sourcing & Event Modeling',
    respond: 'Pilot on low-code and custom dev',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-1',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'Engineer fully involved with the business & AI to speed up development',
    assess: '3 risks:',
    respond: '',
    type: 'Opportunity',
    category: 'Business', // no category listed in row, assuming Business
    distance: 'Assessed',  // no distance listed, assuming Assessed based on risks
    impact: 'Medium',    // not given, default medium
    tolerance: 'Medium', // not given, default medium
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-reasoning',
    radarId: 'team-cto',
    name: 'Reasoning',
    detect: 'Reasoning over Coding',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-lack-of-modelization',
    radarId: 'team-cto',
    name: 'Lack of Modelization',
    detect: 'We do not model; we write specs',
    assess: 'We need to move to modeling techniques and faciliation',
    respond: '',
    type: 'Threat',
    category: 'Operating Model',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-inertia-proxy',
    radarId: 'team-cto',
    name: 'Inertia / Proxy',
    detect: 'We need it will kill us if we do not tackle it',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-flight-levels',
    radarId: 'team-cto',
    name: 'Flight Levels',
    detect: 'We need more coordination',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-event-sourcing',
    radarId: 'team-cto',
    name: 'Event Sourcing',
    detect: 'AI needs context. Data Model loses context. So we need event sourcing',
    assess: 'Simple, works even in a synchronous way with projections',
    respond: 'Go - it is a no-brainer',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-inertia-routine',
    radarId: 'team-cto',
    name: 'Inertia Routine',
    detect: 'Inertia of Routine: Established procedures and methods can limit an organization\'s ability to adapt to changes. For example, deregulation in the airline industry exposed the reliance of airlines on outdated business models, causing significant financial losses until new, adaptive strategies were implemented.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-wrong-practices',
    radarId: 'team-cto',
    name: 'Wrong practices',
    detect: 'We have not evolved.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-agile',
    radarId: 'team-cto',
    name: 'Agile',
    detect: 'We are not agile by doing agile',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-too-technology-focused',
    radarId: 'team-cto',
    name: 'Too technology focused',
    detect: 'We are too deep in technical & architecture thinking. We need to refocus more business-like',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-2',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'New role',
    assess: 'Current roles will have to adapt: BA, PM. Architectures, etc',
    respond: 'Train people on Event Modeling',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Detected',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-accidental-complexity',
    radarId: 'team-cto',
    name: 'Accidental Complexity',
    detect: 'Forget technical debt',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-3',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'test1',
    assess: 'ass12',
    respond: 'res344',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-data-mesh',
    radarId: 'team-cto',
    name: 'Data Mesh',
    detect: 'Way to have data easily, good match with event sourcing',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-event-modeling',
    radarId: 'team-cto',
    name: 'Event Modeling',
    detect: 'Modelling Technique we should use for projects',
    assess: 'We are using specifications, user stories but that kills communication, creating or reinforcing silos',
    respond: 'Go ahead with a pilot project, train people',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
    ],
  },
  {
    id: 'team-cmo',
    name: 'CMO',
    purpose: 'Leads marketing and growth initiatives.',
    context: 'Chief Marketing Officer',
    level: 2,
    dashboard: { id: 'dashboard-cmo', name: 'Marketing & Growth', strategies: [] },
    radar: [],
  },
];


export const strategyStates: {
  value: StrategyState;
  label: string;
  iconName: 'FilePenLine' | 'Rocket' | 'CheckCircle2' | 'Archive';
  colorClass: string;
}[] = [
  { value: 'Draft', label: 'Draft', iconName: 'FilePenLine', colorClass: 'text-blue-600' },
  { value: 'Active', label: 'Active', iconName: 'Rocket', colorClass: 'text-green-600' },
  { value: 'Closed', label: 'Closed', iconName: 'CheckCircle2', colorClass: 'text-gray-500' },
  { value: 'Obsolete', label: 'Obsolete', iconName: 'Archive', colorClass: 'text-gray-500' },
];

export const radarAttributes = {
  types: ['Threat', 'Opportunity'] as RadarItemType[],
  categories: ['Business', 'Operating Model', 'Capabilities', 'People & Knowledge'] as RadarCategory[],
  distances: ['Detected', 'Assessing', 'Assessed', 'Responding'] as RadarDistance[],
  impacts: ['Low', 'Medium', 'High'] as RadarImpact[],
  tolerances: ['High', 'Medium', 'Low'] as RadarTolerance[],
};

export { newInitiativeTemplate };

// Seed initiative links between existing initiatives (optional demo data)
export const initialLinks: { from: string; to: string }[] = [
  // CTO chain
  { from: 'init-1-1', to: 'init-1-2' },
  { from: 'init-1-2', to: 'init-1-3' },
  // Cross org: CEO launch narrative depends on CTO MVP scope
  { from: 'init-ceo-1-1', to: 'init-1-2' },
  // Alignment: CEO OKRs influenced by CTO market research
  { from: 'init-ceo-1-2', to: 'init-1-1' },
  // Board (level 0) influencing CEO (level 1)
  { from: 'init-bod-1', to: 'init-ceo-1-1' },
  { from: 'init-bod-2', to: 'init-ceo-1-2' },
  // Board (level 0) influencing CTO (level 2)
  { from: 'init-bod-1', to: 'init-1-2' },
];
