
import type {
  Team,
  StrategyState,
  RadarItemType,
  RadarCategory,
  RadarDistance,
  RadarImpact,
  RadarTolerance,
  Initiative,
  InitiativeStep,
} from './types';

const newInitiativeTemplate = (id: string, name: string): Initiative => ({
  id,
  name,
  progression: 0,
  steps: initiativeStepsTemplate.map((step) => ({
    key: step.key,
    title: step.title,
    iconName: step.iconName,
    items: [],
  })),
  linkedRadarItemIds: [],
});

const initiativeStepsTemplate: {
  key: 'diagnostic' | 'overallApproach' | 'actions' | 'proximateObjectives';
  title: string;
  iconName: string;
}[] = [
  { key: 'diagnostic', title: 'Diagnostic', iconName: 'Search' },
  { key: 'overallApproach', title: 'Overall Approach', iconName: 'Milestone' },
  { key: 'actions', title: 'Actions', iconName: 'ListChecks' },
  { key: 'proximateObjectives', title: 'Proximate Objectives', iconName: 'Target' },
];

export const initialTeams: Omit<Team, 'companyId'>[] = [
  {
    id: 'team-bod',
    name: 'Board of Directors',
    purpose: 'Oversees the company\'s direction.',
    context: 'Highest governing body.',
    level: 0,
    dashboard: {
      id: 'dashboard-bod',
      name: 'Board-Level Strategic Goals',
      strategies: [
        {
          id: 'bod-strat-1',
          description: 'Grow market share by 5% YoY',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            {
              id: 'init-bod-1',
              name: 'Board Priority: Market Expansion',
              progression: 15,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-bod-2',
              name: 'Board Priority: ESG Disclosure',
              progression: 10,
              steps: [],
              linkedRadarItemIds: [],
            },
          ],
        },
      ],
    },
    radar: [
  {
    id: 'radar-bod-ai-governance',
    radarId: 'team-bod',
    name: 'Blind Spots AI',
    detect: 'Blind Spots in AI Oversight - Regulators are tightening AI oversight and ethical standards.',
    assess: 'High risk if company lacks AI transparency and accountability frameworks.',
    respond: 'Mandate AI governance board and require annual AI audit.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-deglobalization',
    radarId: 'team-bod',
    name: 'Deglobalization',
    detect: 'Deglobalization & RegionalizedTrade restrictions and regional blocs are reshaping supply networks.',
    assess: 'Concentration risk and longer lead times increase operational fragility.',
    respond: 'Map tier-2/3 suppliers, develop nearshoring options, and diversify critical inputs.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-splinternet',
    radarId: 'team-bod',
    name: 'Splinternet',
    detect: 'Fragmented Internet: Divergent data, privacy, and content regimes are fragmenting the web.',
    assess: 'Compliance and product fragmentation risks across jurisdictions.',
    respond: 'Design region-aware services, decouple data residency, and strengthen compliance ops.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-information-asymmetry',
    radarId: 'team-bod',
    name: 'Information Asymmetry',
    detect: 'Information Asymmetry Board ↔ Organization: Boards receive lagging or filtered signals versus frontline realities.',
    assess: 'Decision quality degrades; oversight weakens without transparent flows.',
    respond: 'Establish direct sensing channels, periodic skip-levels, and leading indicator dashboards.',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-overreliance-kpis',
    radarId: 'team-bod',
    name: 'Quantitative KPIs',
    detect: 'Overreliance on Quantitative KPIs: Management culture optimizes numeric targets at the expense of context.',
    assess: 'Tunnel vision and gaming behaviors mask risk and reduce adaptability.',
    respond: 'Balance metrics with narratives; include qualitative reviews and leading signals.',
    type: 'Threat',
    category: 'Operating Model',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-uncertainty-fatigue',
    radarId: 'team-bod',
    name: 'Decision-Making',
    detect: 'Decision-Making Under Uncertainty Fatigue: Persistent ambiguity leads to slower and more conservative choices.',
    assess: 'Opportunity cost rises; strategic optionality decreases.',
    respond: 'Adopt option-based strategies, clarify guardrails, and rotate decision ownership.',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-esg',
    radarId: 'team-bod',
    name: 'ESG Fatigue',
    detect: 'ESG Fatigue & Backlash Risk: Investors and governments increasing ESG reporting pressure.',
    assess: 'Essential for investor confidence and license to operate.',
    respond: 'Integrate ESG metrics into strategic KPIs and executive comp.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-capital-markets',
    radarId: 'team-bod',
    name: 'Resource Scarcity',
    detect: 'Strategic Resource Scarcity (Compute, Energy, Rare Earths)',
    assess: 'TBD',
    respond: 'TBD',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-board-composition',
    radarId: 'team-bod',
    name: 'Digital Literacy',
    detect: 'Board Composition & Digital LiteracyBoards increasingly expected to understand AI and cybersecurity.',
    assess: 'Current board skills gap could slow oversight of digital strategy.',
    respond: 'Recruit directors with data and technology expertise.',
    type: 'Opportunity',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-transparency',
    radarId: 'team-bod',
    name: 'Transparency & Trust',
    detect: 'Transparency & Stakeholder TrustPublic trust in corporations under pressure; rising activism.',
    assess: 'Reputation risk can impact valuation and talent attraction.',
    respond: 'Enhance disclosure practices and stakeholder communication.',
    type: 'Opportunity',
    category: 'People & Knowledge',
    distance: 'Detected',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-bod-echo-chamber',
    radarId: 'team-bod',
    name: 'Echo Chamber',
    detect: 'Agree with CEO without challeging because sounds logical',
    assess: 'We are not having constructive disagreements. We are not challenging the status quo.',
    respond: 'We need to come prepared with alternatives and counterarguments.',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
    {
    id: 'radar-bod-a-strategy',
    radarId: 'team-bod',
    name: 'A strategy',
    detect: 'We should have a strategy to challenge CEO own strategy (see Bambiso Moyo - How boards work',
    assess: 'We need to ba active contributors to the strategy - We need to nuild options',
    respond: 'Have our own radar for situational awareness, better diagnostics',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
],
  },
  {
    id: 'team-ceo',
    name: 'CEO',
    purpose: 'Leads the company and executes the board\'s vision.',
    context: 'Chief Executive Officer.',
    level: 1,
    dashboard: {
      id: 'dashboard-ceo',
      name: 'CEO Directives',
      strategies: [
        {
          id: 'ceo-strat-1',
          description: 'Execute on Q4 2024 Product Launch',
          timeframe: 'Q4 2024',
          state: 'Active',
          initiatives: [
            {
              id: 'init-ceo-1-1',
              name: 'Define launch narrative',
              progression: 20,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-ceo-1-2',
              name: 'Align leadership OKRs',
              progression: 10,
              steps: [],
              linkedRadarItemIds: [],
            },
          ],
        },
        {
          id: 'ceo-strat-2',
          description: 'Improve operational efficiency',
          timeframe: '2025',
          state: 'Draft',
          initiatives: [],
        },
      ],
    },
    radar: [
  {
    id: 'radar-ceo-ai-productivity',
    radarId: 'team-ceo',
    name: 'AI-Driven Productivity',
    detect: 'Competitors achieving efficiency gains through generative AI.',
    assess: 'Significant opportunity to enhance output per employee.',
    respond: 'Deploy AI copilots across key business functions by Q2 2025.',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-talent-retention',
    radarId: 'team-ceo',
    name: 'Talent Retention & Hybrid Work',
    detect: 'Employee engagement declining post-pandemic.',
    assess: 'Attrition risk in high-skill roles; hybrid model inconsistencies.',
    respond: 'Redefine EVP around flexibility, purpose, and growth.',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-innovation-pipeline',
    radarId: 'team-ceo',
    name: 'Innovation Pipeline',
    detect: 'Slow time-to-market for new initiatives.',
    assess: 'Innovation velocity lags competitors.',
    respond: 'Create cross-functional innovation squads with funding autonomy.',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-customer-trust',
    radarId: 'team-ceo',
    name: 'Customer Trust & Data Privacy',
    detect: 'Increasing public concern about data use and AI bias.',
    assess: 'Potential reputational and legal impact.',
    respond: 'Implement privacy-by-design policy and transparency dashboards.',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-operational-efficiency',
    radarId: 'team-ceo',
    name: 'Operational Efficiency',
    detect: 'Duplication and misalignment across divisions.',
    assess: 'Structural inefficiencies reducing agility and profit margins.',
    respond: 'Introduce zero-based design and OKR-driven governance.',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-digital-transformation',
    radarId: 'team-ceo',
    name: 'Digital Transformation Fatigue',
    detect: 'Multiple digital programs without unified vision.',
    assess: 'Risk of initiative overload and cultural resistance.',
    respond: 'Streamline digital portfolio and align with customer value streams.',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-mna-opportunity',
    radarId: 'team-ceo',
    name: 'Strategic M&A Opportunities',
    detect: 'Valuations in target markets have declined.',
    assess: 'Potential for inorganic growth in adjacent technologies.',
    respond: 'Evaluate 2–3 acquisition candidates by Q1 2025.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-ceo-brand-differentiation',
    radarId: 'team-ceo',
    name: 'Brand Differentiation',
    detect: 'Commoditization in our core market.',
    assess: 'Weak differentiation undermines pricing power.',
    respond: 'Pivot brand narrative to innovation, trust, and sustainability.',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
],
  },
  {
    id: 'team-cfo',
    name: 'CFO',
    purpose: 'Manages the company\'s finances.',
    context: 'Chief Financial Officer',
    level: 2,
    dashboard: { id: 'dashboard-cfo', name: 'Financial Strategy', strategies: [] },
    radar: [],
  },
  {
    id: 'team-cto',
    name: 'CTO',
    purpose: 'Leads technology and engineering.',
    context: 'Chief Technology Officer',
    level: 2,
    dashboard: {
      id: 'dashboard-cto-1',
      name: 'Technology Roadmap',
      strategies: [
        {
          id: 'strat-1',
          description: 'Develop and launch the new \'Innovate\' feature set.',
          timeframe: 'Q4 2024',
          state: 'Active',
          initiatives: [
            
            {
              id: 'init-1-2',
              name: 'MVP Scope & Architecture',
              progression: 40,
              steps: [],
              linkedRadarItemIds: [],
            },
            {
              id: 'init-1-4',
              name: 'Software Modeling',
              progression: 0,
              steps: [],
              linkedRadarItemIds: ['radar-item-event-modeling', 'radar-item-lack-of-modelization','radar-item-event-sourcing', 'radar-item-data-mesh'],
            },
            {
              id: 'init-1-5',
              name: 'Events as Data',
              progression: 0,
              steps: [],
              linkedRadarItemIds: ['radar-item-event-sourcing', 'radar-item-data-mesh'],
            },
          ],
        },
        {
          id: 'strat-2',
          description: 'Marketing and go-to-market strategy.',
          timeframe: 'Q4 2024',
          state: 'Draft',
          initiatives: [],
        },
      ],
    },
    radar: [
      {
        id: 'radar-item-1',
        radarId: 'team-cto',
        name: 'AI-driven Automation',
        detect: 'Competitors are leveraging AI to automate customer support.',
        assess: 'This poses a medium-term threat to our market position if we don\'t adapt. It could reduce our operational costs significantly.',
        respond: 'Initiate a pilot project to explore AI chatbot solutions for customer service.',
        type: 'Opportunity',
        category: 'Operating Model',
        distance: 'Detected',
        impact: 'Medium',
        tolerance: 'Medium',
        zoom_in: null,
        created_at: new Date().toISOString(),
        updated_at: null,
      },
      {
    id: 'radar-item-roles-of-sm-ba-pm',
    radarId: 'team-cto',
    name: 'Roles of SM, BA, PM',
    detect: 'What is their role with AI?',
    assess: 'Adaptation required towards facilitators',
    respond: 'trainings',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-cultural-inertia',
    radarId: 'team-cto',
    name: 'Cultural Inertia',
    detect: 'Cultural Inertia: This form refers to deep-rooted norms and mindsets within an organization that resist change. An example is AT&T’s struggle in the mid-1980s to transition from a monopolistic structure to an innovative tech company, hindered by its culture which was focused more on research than on product development.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Detected',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-flow-engineering',
    radarId: 'team-cto',
    name: 'Flow Engineering',
    detect: 'We need to kill silos',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-unit-slices',
    radarId: 'team-cto',
    name: 'Unit / Slices',
    detect: 'Slices (of capabilities) should be our new unit of work/effort',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-driven-spec',
    radarId: 'team-cto',
    name: 'driven spec',
    detect: 'to find ou more',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-ai',
    radarId: 'team-cto',
    name: 'AI',
    detect: 'tactically vs. strategically vs. Hype',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-slice-architecture',
    radarId: 'team-cto',
    name: 'Slice Architecture',
    detect: 'Lack of consistency in the way we design/implement our software solutions. VSA (Vertical Slice Architecture) should give us clear directions',
    assess: 'Easy to understand, works well with Event Sourcing & Event Modeling',
    respond: 'Pilot on low-code and custom dev',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-1',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'Engineer fully involved with the business & AI to speed up development',
    assess: '3 risks:',
    respond: '',
    type: 'Opportunity',
    category: 'Business', // no category listed in row, assuming Business
    distance: 'Assessed',  // no distance listed, assuming Assessed based on risks
    impact: 'Medium',    // not given, default medium
    tolerance: 'Medium', // not given, default medium
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-reasoning',
    radarId: 'team-cto',
    name: 'Reasoning',
    detect: 'Reasoning over Coding',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-lack-of-modelization',
    radarId: 'team-cto',
    name: 'Lack of Modelization',
    detect: 'We do not model; we write specs',
    assess: 'We need to move to modeling techniques and faciliation',
    respond: '',
    type: 'Threat',
    category: 'Operating Model',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-inertia-proxy',
    radarId: 'team-cto',
    name: 'Inertia / Proxy',
    detect: 'We need it will kill us if we do not tackle it',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-flight-levels',
    radarId: 'team-cto',
    name: 'Flight Levels',
    detect: 'We need more coordination',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-event-sourcing',
    radarId: 'team-cto',
    name: 'Event Sourcing',
    detect: 'AI needs context. Data Model loses context. So we need event sourcing',
    assess: 'Simple, works even in a synchronous way with projections',
    respond: 'Go - it is a no-brainer',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-inertia-routine',
    radarId: 'team-cto',
    name: 'Inertia Routine',
    detect: 'Inertia of Routine: Established procedures and methods can limit an organization\'s ability to adapt to changes. For example, deregulation in the airline industry exposed the reliance of airlines on outdated business models, causing significant financial losses until new, adaptive strategies were implemented.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Business',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-wrong-practices',
    radarId: 'team-cto',
    name: 'Wrong practices',
    detect: 'We have not evolved.',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-agile',
    radarId: 'team-cto',
    name: 'Agile',
    detect: 'We are not agile by doing agile',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'People & Knowledge',
    distance: 'Assessing',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-too-technology-focused',
    radarId: 'team-cto',
    name: 'Too technology focused',
    detect: 'We are too deep in technical & architecture thinking. We need to refocus more business-like',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Detected',
    impact: 'Low',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-2',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'New role',
    assess: 'Current roles will have to adapt: BA, PM. Architectures, etc',
    respond: 'Train people on Event Modeling',
    type: 'Opportunity',
    category: 'Business',
    distance: 'Detected',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-accidental-complexity',
    radarId: 'team-cto',
    name: 'Accidental Complexity',
    detect: 'Forget technical debt',
    assess: '',
    respond: '',
    type: 'Threat',
    category: 'Capabilities',
    distance: 'Assessed',
    impact: 'High',
    tolerance: 'Low',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-forward-deployed-engineer-3',
    radarId: 'team-cto',
    name: 'Forward-Deployed Engineer',
    detect: 'test1',
    assess: 'ass12',
    respond: 'res344',
    type: 'Opportunity',
    category: 'Operating Model',
    distance: 'Assessed',
    impact: 'Medium',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-data-mesh',
    radarId: 'team-cto',
    name: 'Data Mesh',
    detect: 'Way to have data easily, good match with event sourcing',
    assess: '',
    respond: '',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Assessing',
    impact: 'Medium',
    tolerance: 'High',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 'radar-item-event-modeling',
    radarId: 'team-cto',
    name: 'Event Modeling',
    detect: 'Modelling Technique we should use for projects',
    assess: 'We are using specifications, user stories but that kills communication, creating or reinforcing silos',
    respond: 'Go ahead with a pilot project, train people',
    type: 'Opportunity',
    category: 'Capabilities',
    distance: 'Responding',
    impact: 'High',
    tolerance: 'Medium',
    zoom_in: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
    ],
  },
  {
    id: 'team-cmo',
    name: 'CMO',
    purpose: 'Leads marketing and growth initiatives.',
    context: 'Chief Marketing Officer',
    level: 2,
    dashboard: { id: 'dashboard-cmo', name: 'Marketing & Growth', strategies: [] },
    radar: [],
  },
  {
    id: 'team-ea',
    name: 'Enterprise Architecture',
    purpose: 'Aligns business goals with technology architecture.',
    context: 'Architecture practice',
    level: 3,
    dashboard: {
      id: 'dashboard-ea',
      name: 'EA Roadmap',
      strategies: [
        {
          id: 'ea-strat-1',
          description: 'Standardize Platforms & Integration',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            { id: 'init-ea-1', name: 'API Platform Governance', progression: 0, steps: [], linkedRadarItemIds: [] },
            { id: 'init-ea-2', name: 'Domain Modeling Handbook', progression: 0, steps: [], linkedRadarItemIds: [] },
          ],
        },
      ],
    },
    radar: [],
  },
  {
    id: 'team-rnd',
    name: 'R&D',
    purpose: 'Explores innovative technologies and prototypes.',
    context: 'Research & Development',
    level: 3,
    dashboard: {
      id: 'dashboard-rnd',
      name: 'Exploration Pipeline',
      strategies: [
        {
          id: 'rnd-strat-1',
          description: 'Prototype Emerging Tech',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            { id: 'init-rnd-1', name: 'Generative AI Assistants', progression: 0, steps: [], linkedRadarItemIds: [] },
            { id: 'init-rnd-2', name: 'LLM Safety & Guardrails', progression: 0, steps: [], linkedRadarItemIds: [] },
          ],
        },
      ],
    },
    radar: [],
  },
  {
    id: 'team-saas',
    name: 'Software Online Services',
    purpose: 'Operates and builds cloud-based products.',
    context: 'SaaS product engineering',
    level: 4,
    dashboard: {
      id: 'dashboard-saas',
      name: 'SaaS Engineering',
      strategies: [
        {
          id: 'saas-strat-1',
          description: 'Reliability & Observability',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            { id: 'init-saas-1', name: 'SLI/SLO Program', progression: 0, steps: [], linkedRadarItemIds: [] },
            { id: 'init-saas-2', name: 'Canary Deployments', progression: 0, steps: [], linkedRadarItemIds: [] },
          ],
        },
      ],
    },
    radar: [],
  },
  {
    id: 'team-custom',
    name: 'Software Custom App',
    purpose: 'Builds bespoke software for customers.',
    context: 'Professional services engineering',
    level: 4,
    dashboard: {
      id: 'dashboard-custom',
      name: 'Custom Delivery',
      strategies: [
        {
          id: 'custom-strat-1',
          description: 'Vertical Slice Delivery',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            { id: 'init-custom-1', name: 'Event-Modeled Delivery', progression: 0, steps: [], linkedRadarItemIds: [] },
            { id: 'init-custom-2', name: 'Automated QA', progression: 0, steps: [], linkedRadarItemIds: [] },
          ],
        },
      ],
    },
    radar: [],
  },
  {
    id: 'team-infra',
    name: 'Infrastructure',
    purpose: 'Provides core platform and networking services.',
    context: 'Platform & Infra',
    level: 4,
    dashboard: {
      id: 'dashboard-infra',
      name: 'Platform Enablement',
      strategies: [
        {
          id: 'infra-strat-1',
          description: 'Platform as a Product',
          timeframe: '2025',
          state: 'Active',
          initiatives: [
            { id: 'init-infra-1', name: 'Self-Service Environments', progression: 0, steps: [], linkedRadarItemIds: [] },
            { id: 'init-infra-2', name: 'Event Bus & Schema Registry', progression: 0, steps: [], linkedRadarItemIds: [] },
          ],
        },
      ],
    },
    radar: [],
  },
];


export const strategyStates: {
  value: StrategyState;
  label: string;
  iconName: 'FilePenLine' | 'Rocket' | 'CheckCircle2' | 'Archive';
  colorClass: string;
}[] = [
  { value: 'Draft', label: 'Draft', iconName: 'FilePenLine', colorClass: 'text-blue-600' },
  { value: 'Active', label: 'Active', iconName: 'Rocket', colorClass: 'text-green-600' },
  { value: 'Closed', label: 'Closed', iconName: 'CheckCircle2', colorClass: 'text-gray-500' },
  { value: 'Obsolete', label: 'Obsolete', iconName: 'Archive', colorClass: 'text-gray-500' },
];

export const radarAttributes = {
  types: ['Threat', 'Opportunity'] as RadarItemType[],
  categories: ['Business', 'Operating Model', 'Capabilities', 'People & Knowledge'] as RadarCategory[],
  distances: ['Detected', 'Assessing', 'Assessed', 'Responding'] as RadarDistance[],
  impacts: ['Low', 'Medium', 'High'] as RadarImpact[],
  tolerances: ['High', 'Medium', 'Low'] as RadarTolerance[],
};

export { newInitiativeTemplate };

// Seed initiative links between existing initiatives (optional demo data)
export const initialLinks: { from: string; to: string }[] = [
  // CTO chain
  // (removed link to removed initiative init-1-3)
  // Cross org: CEO launch narrative depends on CTO MVP scope
  { from: 'init-ceo-1-1', to: 'init-1-2' },
  // Alignment: CEO OKRs influenced by CTO work
  // Board (level 0) influencing CEO (level 1)
  { from: 'init-bod-1', to: 'init-ceo-1-1' },
  { from: 'init-bod-2', to: 'init-ceo-1-2' },
  // Board (level 0) influencing CTO (level 2)
  { from: 'init-bod-1', to: 'init-1-2' },
  // Board (level 0) influencing Level 3 (EA, R&D)
  { from: 'init-bod-1', to: 'init-ea-2' },
  { from: 'init-bod-2', to: 'init-ea-1' },
  { from: 'init-bod-1', to: 'init-rnd-1' },
  // CEO (level 1) guiding CTO (level 2)
  { from: 'init-ceo-1-1', to: 'init-1-4' },
  { from: 'init-ceo-1-2', to: 'init-1-5' },
  // CTO (level 2) influencing Level 3 (EA) and Level 4 teams
  { from: 'init-1-4', to: 'init-ea-2' },
  { from: 'init-1-4', to: 'init-custom-1' },
  { from: 'init-1-5', to: 'init-infra-2' },
  { from: 'init-1-5', to: 'init-saas-2' },
  { from: 'init-1-2', to: 'init-saas-1' },
  // EA (level 3) enabling Level 4 teams
  { from: 'init-ea-1', to: 'init-infra-1' },
  { from: 'init-ea-1', to: 'init-saas-1' },
  { from: 'init-ea-2', to: 'init-custom-1' },
  // R&D (level 3) seeding experiments into Level 4
  { from: 'init-rnd-1', to: 'init-saas-2' },
  { from: 'init-rnd-2', to: 'init-infra-2' },
  // Platform (infra) supporting SaaS
  { from: 'init-infra-1', to: 'init-saas-1' },
  // Upward chains: L4 -> L3 -> L2 -> L1 -> L0
  // SaaS Canary -> EA Modeling -> CTO Event Sourcing -> CEO OKRs -> Board Priority
  { from: 'init-saas-2', to: 'init-ea-2' },
  { from: 'init-ea-2', to: 'init-1-5' },
  { from: 'init-1-5', to: 'init-ceo-1-2' },
  { from: 'init-ceo-1-2', to: 'init-bod-1' },
  // Custom Delivery -> EA Modeling -> CTO Software Modeling -> CEO Narrative -> Board ESG
  { from: 'init-custom-1', to: 'init-ea-2' },
  { from: 'init-ea-2', to: 'init-1-4' },
  { from: 'init-1-4', to: 'init-ceo-1-1' },
  { from: 'init-ceo-1-1', to: 'init-bod-2' },
  // Infra Event Bus -> EA API Governance -> CTO MVP Scope -> CEO OKRs -> Board Market Expansion
  { from: 'init-infra-2', to: 'init-ea-1' },
  { from: 'init-ea-1', to: 'init-1-2' },
  { from: 'init-1-2', to: 'init-ceo-1-2' },
  { from: 'init-ceo-1-2', to: 'init-bod-1' },
];
