-- SQL script to insert radar items for the CTO team (team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef)

-- Delete existing radar items for this team to prevent duplicates if script is run multiple times
DELETE FROM events WHERE aggregate_id = 'team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef' AND event_type LIKE 'RadarItem%';

-- Insert new radar items
INSERT INTO events (aggregate_id, entity_type, event_type, payload, "timestamp") VALUES
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-1", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Roles of SM", "detect": "What is the Adaptation trainings", "assess": "Identify gaps in current training programs.", "respond": "Develop new training materials.", "type": "Threat", "category": "People & Knowledge", "distance": "Assessing", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-2", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Cultural Inertia", "detect": "This form refers to resistance to change.", "assess": "Analyze the root causes of cultural inertia.", "respond": "Launch change management initiatives.", "type": "Threat", "category": "Business", "distance": "Detected", "impact": "Medium", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-3", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Flow Engin", "detect": "We need to kill silos", "assess": "Map out existing cross-departmental workflows.", "respond": "Implement new collaborative tools.", "type": "Opportunity", "category": "Operating Model", "distance": "Assessing", "impact": "Medium", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-4", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Unit / Slice", "detect": "Slices (of capabilities) should be driven to find out more", "assess": "Define the scope and criteria for capability slicing.", "respond": "Pilot a project using the capability slicing model.", "type": "Opportunity", "category": "Capabilities", "distance": "Detected", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-5", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "AI", "detect": "Tactically vs. strategically vs. Hybrid", "assess": "Evaluate the pros and cons of different AI adoption strategies.", "respond": "Develop a clear AI strategy roadmap.", "type": "Threat", "category": "People & Knowledge", "distance": "Assessing", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-6", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Slice Architecture", "detect": "Lack of collaboration, easy to understand, pilot on love", "assess": "Assess the feasibility of a pilot project for a new slice architecture.", "respond": "Launch a pilot project with a dedicated team.", "type": "Opportunity", "category": "Capabilities", "distance": "Assessed", "impact": "Medium", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-7", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Forward-D Engineer", "detect": "Engineer faces 3 risks", "assess": "Identify and categorize the top three risks for forward-deployed engineers.", "respond": "Develop mitigation plans for each identified risk.", "type": "Threat", "category": "People & Knowledge", "distance": "Detected", "impact": "High", "tolerance": "Low", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-8", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Reasoning", "detect": "Reasoning over Coding", "assess": "Promote a culture that values strong reasoning and analytical skills.", "respond": "Incorporate reasoning exercises into the hiring process.", "type": "Threat", "category": "Capabilities", "distance": "Assessing", "impact": "High", "tolerance": "Low", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-9", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Lack of motivation", "detect": "We do not want to move to new tech", "assess": "Understand the reasons behind the resistance to new technologies.", "respond": "Provide training and highlight the benefits of new tech.", "type": "Threat", "category": "Operating Model", "distance": "Assessing", "impact": "Medium", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-10", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Inertia / Pride", "detect": "We need it or it will kill us if we do not", "assess": "Assess the competitive landscape and the urgency for change.", "respond": "Communicate the critical need for adaptation to the team.", "type": "Threat", "category": "Business", "distance": "Assessing", "impact": "High", "tolerance": "Low", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-11", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Flight Level", "detect": "We need more coordination", "assess": "Identify areas where coordination is lacking.", "respond": "Implement regular cross-functional team meetings.", "type": "Opportunity", "category": "Operating Model", "distance": "Detected", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-12", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Event Sourcing", "detect": "AI needs clean, simple, wc Go - it is a", "assess": "Evaluate the benefits of event sourcing for AI data processing.", "respond": "Design a proof-of-concept for an event-sourced data pipeline.", "type": "Opportunity", "category": "Business", "distance": "Assessed", "impact": "High", "tolerance": "Low", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-13", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Inertia of Routine", "detect": "Established processes are hard to change.", "assess": "Review and identify outdated or inefficient processes.", "respond": "Introduce incremental changes to existing routines.", "type": "Threat", "category": "Business", "distance": "Assessing", "impact": "Medium", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-14", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Wrong practices", "detect": "We have not evolved.", "assess": "Audit current practices against industry best practices.", "respond": "Schedule workshops to introduce modern development methodologies.", "type": "Threat", "category": "Capabilities", "distance": "Detected", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-15", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Agile", "detect": "We are not agile by doing agile", "assess": "Evaluate the team''s understanding and implementation of agile principles.", "respond": "Organize an agile refresher course with a focus on mindset.", "type": "Threat", "category": "People & Knowledge", "distance": "Assessing", "impact": "High", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-16", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Too technical", "detect": "We are too deep in technical & architecture", "assess": "Assess the balance between technical and business-focused discussions.", "respond": "Involve product managers more closely in technical planning.", "type": "Threat", "category": "Capabilities", "distance": "Detected", "impact": "Low", "tolerance": "High", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-17", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Forward-D New role", "detect": "Current role train people", "assess": "Define the responsibilities and skill requirements for the new role.", "respond": "Create a training program for employees transitioning to the new role.", "type": "Opportunity", "category": "Business", "distance": "Detected", "impact": "High", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-18", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Accidental Debt", "detect": "Forget technical debt", "assess": "Quantify the existing technical debt and its impact.", "respond": "Allocate dedicated time in each sprint for addressing technical debt.", "type": "Threat", "category": "Capabilities", "distance": "Assessed", "impact": "High", "tolerance": "Low", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW()),
('team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef', 'team', 'RadarItemCreated', '{"id": "radar-item-19", "radarId": "team-a264c791-3fbe-4a8d-a3a8-bf468d9b11ef", "name": "Event Modeling", "detect": "We are using Go ahead", "assess": "Explore the advantages of event modeling for our system architecture.", "respond": "Conduct a workshop on event modeling with the development team.", "type": "Opportunity", "category": "Capabilities", "distance": "Responding", "impact": "High", "tolerance": "Medium", "zoom_in": null, "created_at": "2024-01-01T00:00:00.000Z"}', NOW());
